<?xml version="1.0" encoding="utf-8"?><Database Name="G:\VISUALSTUDIOCODES\BLOODBANK\BLOODBANKWITHUNITTESTING\BLOODBANKWITHUNITTESTING\APP_DATA\BLOODBANKDATABASE.MDF" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=G:\VISUALSTUDIOCODES\BLOODBANK\BLOODBANKWITHUNITTESTING\BLOODBANKWITHUNITTESTING\APP_DATA\BLOODBANKDATABASE.MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="G__VISUALSTUDIOCODES_BLOODBANK_BLOODBANKWITHUNITTESTING_BLOODBANKWITHUNITTESTING_APP_DATA_BLOODBANKDATABASE_MDFConnectio" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bloodDonateRecords" Member="bloodDonateRecords">
    <Type Name="bloodDonateRecord">
      <Column Name="recordNo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="donor_id" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="client_id" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="blood_group" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="donationDate" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="user_profile_info_bloodDonateRecord" Member="user_profile_info" ThisKey="client_id" OtherKey="user_PID" Type="user_profile_info" IsForeignKey="true" />
      <Association Name="user_profile_info_bloodDonateRecord1" Member="user_profile_info1" ThisKey="donor_id" OtherKey="user_PID" Type="user_profile_info" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_login" Member="user_logins">
    <Type Name="user_login">
      <Column Name="user_mail" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_pass" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="reg_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="activity" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Association Name="user_login_user_profile_info" Member="user_profile_infos" ThisKey="user_mail" OtherKey="userMail" Type="user_profile_info" />
    </Type>
  </Table>
  <Table Name="dbo.user_notification" Member="user_notifications">
    <Type Name="user_notification">
      <Column Name="notificationId" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="notificationTime" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="messange" Type="System.String" DbType="Text" CanBeNull="true" />
      <Association Name="user_profile_info_user_notification" Member="user_profile_info" ThisKey="userId" OtherKey="user_PID" Type="user_profile_info" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_profile_info" Member="user_profile_infos">
    <Type Name="user_profile_info">
      <Column Name="user_PID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="userMail" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="dob" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="userAddress" Type="System.String" DbType="VarChar(36)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="bloodGroup" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="user_profile_info_bloodDonateRecord" Member="bloodDonateRecords" ThisKey="user_PID" OtherKey="client_id" Type="bloodDonateRecord" />
      <Association Name="user_profile_info_bloodDonateRecord1" Member="bloodDonateRecords1" ThisKey="user_PID" OtherKey="donor_id" Type="bloodDonateRecord" />
      <Association Name="user_profile_info_user_notification" Member="user_notifications" ThisKey="user_PID" OtherKey="userId" Type="user_notification" />
      <Association Name="user_login_user_profile_info" Member="user_login" ThisKey="userMail" OtherKey="user_mail" Type="user_login" IsForeignKey="true" />
    </Type>
  </Table>
</Database>